In [127]:
import numpy as np
import seaborn as sns

In [201]:
evolution_rate = 0.1

test = np.random.normal(loc=0, scale=evolution_rate, size=1000)

In [205]:
tests = np.random.rand(10) - 0.5
tests

array([ 0.37255217,  0.16710657, -0.10516767,  0.11007207,  0.36163754,
       -0.00893542, -0.10821911,  0.24076121, -0.0951294 ,  0.15548089])

In [222]:
evolution_rate = 0.1

def applyEvolution(n, evolution_rate):

    m = n + 0.5
    m *= np.random.normal(loc=1, scale=evolution_rate, size=1)
    m -= 0.5

    return m

nn = []

for t in tests:
    nn.append(applyEvolution(t, evolution_rate))

nn

[array([0.35736432]),
 array([0.24448889]),
 array([-0.14609308]),
 array([0.14549772]),
 array([0.34746545]),
 array([0.03462188]),
 array([-0.08815824]),
 array([0.17764616]),
 array([-0.08523873]),
 array([0.18101467])]

In [149]:
# Base class
class Layer:
    def __init__(self):
        self.input = None
        self.output = None

    # computes the output Y of a layer for a given input X
    def forward_propagation(self, input):
        raise NotImplementedError
        
        
# Fully Connected Laye
class FCLayer(Layer):
    # input_size = number of input neurons
    # output_size = number of output neurons
    def __init__(self, input_size, output_size):
        self.weights = np.random.rand(input_size, output_size) - 0.5
        self.bias = np.random.rand(1, output_size) - 0.5

    # returns output for a given input
    def forward_propagation(self, input_data):
        self.input = input_data
        self.output = np.dot(self.input, self.weights) + self.bias
        return self.output

    def evolve(self, evolution_rate):
        for i, weight in enumerate(self.weights):
            self.weights[i] *= np.random.normal(loc=1, scale=evolution_rate, size=1)
        for i, bias in enumerate(self.bias):
            self.bias[i] *= np.random.normal(loc=1, scale=evolution_rate, size=1)
    
    
# Activation Layer
class ActivationLayer(Layer):
    def __init__(self, activation, activation_prime):
        self.activation = activation
        self.activation_prime = activation_prime

    # returns the activated input
    def forward_propagation(self, input_data):
        self.input = input_data
        self.output = self.activation(self.input)
        return self.output

    def evolve(self, evolution_rate):
        pass

    
# activation function and its derivative
def tanh(x):
    return np.tanh(x)

def tanh_prime(x):
    return 1-np.tanh(x)**2


class Network:
    def __init__(self):
        self.layers = []
        self.loss = None
        self.loss_prime = None

    # add layer to network
    def add(self, layer):
        self.layers.append(layer)

    def evolve(self, evolution_rate):
        for layer in self.layers:
            layer.evolve(evolution_rate)

    # predict output for given input
    def predict(self, input_data):

        result = []

        output = input_data

        # forward propagation
        for layer in self.layers:
            output = layer.forward_propagation(output)

            
        result.append(output)

        return result

In [43]:
input = [
    75,     # health
    3,      # food
    0,
    0
]

# example output
output = [
    0.1,     # rotate
    0.6    # forward speed
]

In [150]:
# network
net = Network()
net.add(FCLayer(4, 4))
net.add(ActivationLayer(tanh, tanh_prime))
net.add(FCLayer(4, 2))
net.add(ActivationLayer(tanh, tanh_prime))

out = net.predict(input)

out



[array([[ 0.85825698, -0.48242145]])]

In [151]:
input = [
    50,     # health
    3,      # food
    0,
    10
]

out = net.predict(input)

out

[array([[ 0.85825698, -0.48242145]])]

In [190]:
input = [
    50,     # health
    3,      # food
    0,
    10
]

net.evolve(evolution_rate=0.1)

out = net.predict(input)

out

[array([[ 0.89773181, -0.55211815]])]

In [59]:
print("Weights")
print(net.layers[0].weights)

print("Bias")
print(net.layers[0].bias)

print()

print("Activation")
print(net.layers[1].activation)

print("ACtivation Prime")
print(net.layers[1].activation_prime)

print()

print("Weights")
print(net.layers[2].weights)

print("Bias")
print(net.layers[2].bias)

print()

print("Activation")
print(net.layers[3].activation)

print("ACtivation Prime")
print(net.layers[3].activation_prime)

Weights
[[-0.45277553  0.36854566  0.3197564   0.47522099]
 [ 0.2417056  -0.34621124  0.24913906 -0.10721236]
 [ 0.29196698 -0.48446242  0.21071066  0.28477073]
 [-0.26225605  0.33528059  0.05173828 -0.0770673 ]]
Bias
[[ 0.2694736   0.34840061  0.46478432 -0.35399001]]

Activation
<function tanh at 0x000002866E32AB00>
ACtivation Prime
<function tanh_prime at 0x000002867D8FC1F0>

Weights
[[ 0.33746061 -0.03092476]
 [-0.07570809  0.02957056]
 [ 0.14266927 -0.32458779]
 [ 0.14996964  0.36825241]]
Bias
[[0.20228765 0.15207427]]

Activation
<function tanh at 0x000002866E32AB00>
ACtivation Prime
<function tanh_prime at 0x000002867D8FC1F0>


In [198]:
def vectorFromAngle(a):
    return [np.cos(a), np.sin(a)]

def scaleVector(vector, length):
    f = length / np.linalg.norm(vector)
    return [f * i for i in vector]

angle = -1
scale = 0.1

scaleVector(vectorFromAngle(angle), scale)

[0.05403023058681398, -0.08414709848078966]

In [9]:
import calc
import math
import numpy as np

E = [0,0]           # start of line
L = [0.5,0.5]       # end of line

C = [1, 1]          # centre of circle
r = 0.8             # radius

d = calc.subVectors(L, E)       # direction vector of ray from start to end
f = calc.subVectors(E, C)       # vector from centre circle to ray start

a = np.dot(d, d)
b = 2 * np.dot(f, d)
c = np.dot(f, f) - r*r

disc = b*b - 4 * a * c

hit = 0

if disc >= 0:

    disc = math.sqrt(disc)
    t1 = (-b - disc) / (2 * a)
    t2 = (-b + disc) / (2 * a)

    if (t1 >= 0) & (t1 <= 1):
        hit = 1

    elif (t2 >= 0) & (t2 <= 1):
        hit = 1


a, b, c, disc, hit


(0.5, -2.0, 1.3599999999999999, 1.1313708498984762, 1)

In [10]:
calc.lineIntersectsCircle(E, L, C, r)

1

In [2]:
import calc

v1 = [1, 1]
v2 = [1, 2]

th = calc.signedTheta(v1, v2)

th

0.3217505543966423